/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IConversionRouterV2Interface extends ethers.utils.Interface {
  functions: {
    "depositStable(uint256)": FunctionFragment;
    "finish(address)": FunctionFragment;
    "finishDepositStable(address)": FunctionFragment;
    "finishRedeemStable(address)": FunctionFragment;
    "init(uint8,address,uint256,address,address,bool)": FunctionFragment;
    "initDepositStable(uint256,address,address)": FunctionFragment;
    "initRedeemStable(uint256)": FunctionFragment;
    "redeemStable(address,uint256,address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "depositStable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "finish", values: [string]): string;
  encodeFunctionData(
    functionFragment: "finishDepositStable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "finishRedeemStable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [BigNumberish, string, BigNumberish, string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "initDepositStable",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initRedeemStable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemStable",
    values: [string, BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "finish", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finishDepositStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finishRedeemStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initDepositStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initRedeemStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemStable",
    data: BytesLike
  ): Result;

  events: {};
}

export class IConversionRouterV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IConversionRouterV2Interface;

  functions: {
    "depositStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "depositStable(address,uint256)"(
      _operator: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "depositStable(address,uint256,address,address)"(
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    finish(
      _operation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    finishDepositStable(
      _operation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    finishRedeemStable(
      _operation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    init(
      _type: BigNumberish,
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      _autoFinish: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initDepositStable(uint256,address,address)"(
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initDepositStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initRedeemStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initRedeemStable(uint256,address,address)"(
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "redeemStable(address,uint256,address,address)"(
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "redeemStable(address,uint256)"(
      _operator: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "redeemStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  "depositStable(uint256)"(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "depositStable(address,uint256)"(
    _operator: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "depositStable(address,uint256,address,address)"(
    _operator: string,
    _amount: BigNumberish,
    _swapper: string,
    _swapDest: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  finish(
    _operation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  finishDepositStable(
    _operation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  finishRedeemStable(
    _operation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  init(
    _type: BigNumberish,
    _operator: string,
    _amount: BigNumberish,
    _swapper: string,
    _swapDest: string,
    _autoFinish: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initDepositStable(uint256,address,address)"(
    _amount: BigNumberish,
    _swapper: string,
    _swapDest: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initDepositStable(uint256)"(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initRedeemStable(uint256)"(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initRedeemStable(uint256,address,address)"(
    _amount: BigNumberish,
    _swapper: string,
    _swapDest: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "redeemStable(address,uint256,address,address)"(
    _operator: string,
    _amount: BigNumberish,
    _swapper: string,
    _swapDest: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "redeemStable(address,uint256)"(
    _operator: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "redeemStable(uint256)"(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    "depositStable(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "depositStable(address,uint256)"(
      _operator: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "depositStable(address,uint256,address,address)"(
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: CallOverrides
    ): Promise<string>;

    finish(_operation: string, overrides?: CallOverrides): Promise<void>;

    finishDepositStable(
      _operation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    finishRedeemStable(
      _operation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    init(
      _type: BigNumberish,
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      _autoFinish: boolean,
      overrides?: CallOverrides
    ): Promise<string>;

    "initDepositStable(uint256,address,address)"(
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "initDepositStable(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "initRedeemStable(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "initRedeemStable(uint256,address,address)"(
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "redeemStable(address,uint256,address,address)"(
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "redeemStable(address,uint256)"(
      _operator: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "redeemStable(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    "depositStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "depositStable(address,uint256)"(
      _operator: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "depositStable(address,uint256,address,address)"(
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    finish(
      _operation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    finishDepositStable(
      _operation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    finishRedeemStable(
      _operation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    init(
      _type: BigNumberish,
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      _autoFinish: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initDepositStable(uint256,address,address)"(
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initDepositStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initRedeemStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initRedeemStable(uint256,address,address)"(
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "redeemStable(address,uint256,address,address)"(
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "redeemStable(address,uint256)"(
      _operator: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "redeemStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "depositStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "depositStable(address,uint256)"(
      _operator: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "depositStable(address,uint256,address,address)"(
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    finish(
      _operation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    finishDepositStable(
      _operation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    finishRedeemStable(
      _operation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    init(
      _type: BigNumberish,
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      _autoFinish: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initDepositStable(uint256,address,address)"(
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initDepositStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initRedeemStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initRedeemStable(uint256,address,address)"(
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "redeemStable(address,uint256,address,address)"(
      _operator: string,
      _amount: BigNumberish,
      _swapper: string,
      _swapDest: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "redeemStable(address,uint256)"(
      _operator: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "redeemStable(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
