/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Operator, OperatorInterface } from "../Operator";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "checkGranted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "checkOperator",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "checkOwner",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "operator",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_operator",
        type: "address",
      },
    ],
    name: "transferOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610019610066565b600080546001600160a01b0319166001600160a01b0392909216919091179055610041610066565b600180546001600160a01b0319166001600160a01b039290921691909117905561006a565b3390565b6102af806100796000396000f3fe608060405234801561001057600080fd5b506004361061007d5760003560e01c80638da5cb5b1161005b5780638da5cb5b146100ca578063cdbce03d146100d2578063e30babb4146100da578063f2fde38b146100e25761007d565b806329605e7714610082578063570ca735146100975780637a4eade4146100b5575b600080fd5b61009561009036600461021e565b6100f5565b005b61009f610151565b6040516100ac919061024c565b60405180910390f35b6100bd610160565b6040516100ac9190610260565b61009f61017d565b6100bd61018c565b6100bd6101b0565b6100956100f036600461021e565b6101c7565b6100fd61018c565b6101225760405162461bcd60e51b81526004016101199061026b565b60405180910390fd5b6001805473ffffffffffffffffffffffffffffffffffffffff19166001600160a01b0392909216919091179055565b6001546001600160a01b031681565b600061016a61018c565b8061017857506101786101b0565b905090565b6000546001600160a01b031681565b600080546001600160a01b03166101a161021a565b6001600160a01b031614905090565b6001546000906001600160a01b03166101a161021a565b6101cf61018c565b6101eb5760405162461bcd60e51b81526004016101199061026b565b6000805473ffffffffffffffffffffffffffffffffffffffff19166001600160a01b0392909216919091179055565b3390565b60006020828403121561022f578081fd5b81356001600160a01b0381168114610245578182fd5b9392505050565b6001600160a01b0391909116815260200190565b901515815260200190565b6020808252601d908201527f4f70657261746f723a206f776e6572206163636573732064656e69656400000060408201526060019056fea164736f6c6343000705000a";

export class Operator__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Operator> {
    return super.deploy(overrides || {}) as Promise<Operator>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Operator {
    return super.attach(address) as Operator;
  }
  connect(signer: Signer): Operator__factory {
    return super.connect(signer) as Operator__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OperatorInterface {
    return new utils.Interface(_abi) as OperatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Operator {
    return new Contract(address, _abi, signerOrProvider) as Operator;
  }
}
